--file_board sql
create	table file (
	FILE_NUM	NUMBER	(5)	primary key	,
	FILE_NAME	VARCHAR2	(30), 
	FILE_PASS	NUMBER	(30)	,
	FILE_SUBJECT	VARCHAR2	(300)	,	
	FILE_CONTENT	VARCHAR2	(4000)	,		
	FILE_FILE	VARCHAR2	(50)		,
	FILE_FILE2	VARCHAR2	(50)	,		
	FILE_RE_REF	 NUMBER	(5)			,	
	FILE_RE_LEV	NUMBER(5)			,	
	FILE_RE_SEQ		NUMBER	(5)		,
	FILE_READCOUNT		NUMBER(5)		,
	FILE_DATE	DATE				SYSDATE);